### PR TITLE
Force UTF8 request and response

### PR DESCRIPTION
**Pull request by Narrat**
Else there will be wrong decoded chars

_______

Noticed no problems with the options for both python versions.
All working well for me, and issues like that https://github.com/Narrat/translate/issues/7 shouldn't become a problem.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you for this change!

**Comment by jarun** [comment]
Any idea how we can show %22 as " (double quotes)?
For example:
https://en.wikipedia.org/wiki/%22Hello,_World!%22_program
should be
https://en.wikipedia.org/wiki/"Hello,_World!"_program

**Comment by Narrat** [comment]
If it doesn't brake the url (using terminal for opening it, or program) you could try to use unquote from urllib.parse at https://github.com/jarun/google-cli/blob/master/google#L142

**Comment by jarun** [comment]
I am already using it at
https://github.com/jarun/google-cli/blob/master/google#L127

Will give it a rest or now. BTW, I have done some more testing and found no problems with Python 2.7.x or 3.x. Will release version 1.1 soon with your contributions. :)

**Comment by Narrat** [comment]
I obviously missed that too *cough*
Remaining method I currently can think of:
After the unquote put
> url = url.replace("%22", "\"")

**Comment by jarun** [comment]
I will test if it opens correctly in the browser. In the worst case will ave it as it is.

**Comment by jarun** [comment]
Works! Awesome! ;)

**Pull request merged**
